### ISSUE TITLE
Registering custom components in angular 6

### ISSUE THREAD

**Issue by sriram275** [formio/angular-demo#1]
Hi,
Checked out this repository and everything working fine.
Trying to create and register custom component here with help of your gist
[https://gist.github.com/travist/59fa77086ec899e24992fc1508e61075](https://gist.github.com/travist/59fa77086ec899e24992fc1508e61075)

Registering like:
FormioForm.registerComponent('checkmatrix', CheckMatrix);

But FormioForm doesn't have registerComponent method or might be import statement wrong
import { FormioForm } from 'angular-formio';

Let me know how to handle this?

Thanks.

**Comment by merobal** [comment]
See this as example: https://github.com/formio/angular-formio/wiki/Custom-Components-with-Angular-Elements#register-a-single-class-as-custom-component
