### ISSUE TITLE
Bootstrap 3 Form Builder

### ISSUE THREAD

**Issue by sezerkorkmaz** [formio/angular-demo#10]
Is there a bootstrap 3 version of this demo? Couldn't find any theme for this demo. Is there a config to set template as bootstrap 3?

this is not working.
```
import { Templates } from 'formiojs';
Templates.framework = 'bootstrap3';
```

**Comment by sezerkorkmaz** [comment]
After several hours. I finally found a solution like this.
import * as af from 'angular-formio';
af.Formio.Templates.framework = 'bootstrap3';

**Comment by travist** [comment]
We will need to add this to documentation @ https://github.com/formio/angular-formio wiki.

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
