### ISSUE TITLE
[QUESTION] FormBuilder > How to remove/disable unnecessary component options

### ISSUE THREAD

**Issue by ashleyasli** [formio/angular-demo#11]
Hello all,

I need to remove/disable form-builder tab’s internal options like “Placeholder”, "Widget", "Tool-tip" etc. I am using angular-demo as base. How do I disable these portions I crossed out in the image below?

![image](https://user-images.githubusercontent.com/43186823/67421361-ee646580-f595-11e9-91b2-f3a1e4202cbc.png)
  
I will appreciate it if you can answer my question with an example.
 
Thanks in advance for any helps

**Comment by ashleyasli** [comment]
Here is the solution: 

```"editForm": {
              "textfield": [
              {
                  "key": "display",
                  "ignore": false,
                  "components": [
                      {
                          "key": "placeholder",
                          "ignore": true
                      },
                      {
                        "key": "tooltip",
                        "ignore": true
                      },
                      {
                        "key": "widget",
                        "ignore": true
                      }
                  ]
              }      
          ]
        }

**Comment by Achyuthkodali** [comment]
Can We ignore those components for all types fields at a time?

**Comment by ASHIK5261** [comment]
@ashleyasli its heped me. Thanks

**Comment by Quartzbell** [comment]
This is exactly what I'm looking for for hours.
Thank you @ashleyasli!

**Comment by Ankita-G-Mudgal** [comment]
thank you.. @ashleyasli

**Comment by msrmsr621** [comment]
@Ankita-G-Mudgal @Quartzbell @ASHIK5261 @Achyuthkodali @ashleyasli 

> Here is the solution:
> 
> ```
> "editForm": {
>               "textfield": [
>               {
>                   "key": "display",
>                   "ignore": false,
>                   "components": [
>                       {
>                           "key": "placeholder",
>                           "ignore": true
>                       },
>                       {
>                         "key": "tooltip",
>                         "ignore": true
>                       },
>                       {
>                         "key": "widget",
>                         "ignore": true
>                       }
>                   ]
>               }      
>           ]
>         }              
> ```

How to add custom components under textField.
I need to add one checkbox name will be "isSearchable".
is it possible?
please help me
