### ISSUE TITLE
[BUG] TypeError: Cannot set property 'key' of undefined (CheckMatrix)

### ISSUE THREAD

**Issue by ashleyasli** [formio/angular-demo#12]
## Environment
Hosting type: Local deployment

npm: 6.11.3

Global packages:
@angular/cli@8.3.10
angular-formio: 4.2.8

OS:
Windows 10

## Steps to Reproduce
1. `git clone git@github.com:formio/angular-demo.git`
2. npm install -g @angular/cli
3. npm install
4. Implemented #9 solution to the project

## Expected behavior
Successful compilation
## Observed behavior
I tried to implement "Checkmatrix" component into the form-builder. Form-builder didn't appear and I got this error message. (Seen below)

![image](https://user-images.githubusercontent.com/43186823/67296823-a1f22a80-f4ae-11e9-889c-20a7ecc01e8c.png)

## Form-builder part
I defined the form-builder like this: 

```
<form-builder [options]= '{
  "builder": {
    "basic": false,
    "advanced": false,
    "data": false,
    "layout": false,  
    "customBasic": {      
      "title": "Basic Components",
      "weight": 0,
      "default": false,      
      "components": {  
        "checkmatrix": true
      }
    }    
}}'
[form]="form" class="formio" (change)="onChange($event)"></form-builder>
```

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
