### ISSUE TITLE
Checkmatrix output on Firefox/Chrome 

### ISSUE THREAD

**Issue by dmenne** [formio/angular-demo#13]
[Checkmatrix output](https://github.com/formio/angular-demo/blob/master/src/app/components/CheckMatrix.js) looks good on chrome (first, nice large buttons for tablet), but standard on Firefox

![chrome](https://user-images.githubusercontent.com/506275/68663253-9f7b7180-053e-11ea-8feb-e0f8f4e240d8.png)
![firefox](https://user-images.githubusercontent.com/506275/68663258-a1ddcb80-053e-11ea-91f3-55b0f8505bc9.png)

**Comment by travist** [comment]
checkmatrix is just a "demo" component that shows how to build custom components. It was never intended to be a "production" ready component.
