### ISSUE TITLE
Not working on mozilla firefox

### ISSUE THREAD

**Issue by anoopsurendrananp** [formio/angular-demo#15]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [x] Local deployment 
- angular-formio version: 4.3.11
- Frontend framework: Angular
- Angular CLI version: 8.3.20

## Steps to Reproduce
1. clone or download this repo
2. install dependencies using the command npm install 
3. Open Mozilla firefox and go to http:localhost:4200

## Expected behavior
The application works without errors on chrome browser. A similar behaviour is expected 
## Observed behavior
It displays nothing on Mozilla Firefox. 

On console there is an error:
```Error: "Zone.js has detected that ZoneAwarePromise `(window|global).Promise` has been overwritten.
Most likely cause is that a Promise polyfill has been loaded after Zone.js (Polyfilling Promise api is not necessary when zone.js is loaded. If you must load one, do so before loading zone.js.)"```

`Angular 5
assertZonePatched
NgZone
getNgZone
bootstrapModuleFactory
bootstrapModule

notify es.promise.js:114`

The link https://formio.github.io/angular-demo/ works fine in mozilla environment, but when it is downloaded or clonned Mozilla displays a blank screen along with the above error on the console.

**Comment by travist** [comment]
We will update with the latest version since I believe there were some versions that introduced Promise collisions.

**Comment by anoopsurendrananp** [comment]
Thank you for the quick response @travist. When we can expect the next version?

**Comment by rajuvelayudhan** [comment]
@travist I am also facing the same issue. Appreciate if you could update the latest version ASAP. Thanks

**Comment by travist** [comment]
Fixed with latest versions.

**Comment by anoopsurendrananp** [comment]
Thanks for the update, @travist. 
Now its working fine in Mozilla Firefox.

**Comment by sahan-gjs** [comment]
Facing the same issue here on Angular 11 and Form.IO version 4.11.5
