### ISSUE TITLE
[BUG] : Initial value is not set for the textField when allowOverride of calculateValue option is checked.

### ISSUE THREAD

**Issue by AmeeBhadania** [formio/angular-demo#25]
Steps to reproduce :

Download angular-demo project from https://github.com/formio/angular-demo as a zip file. In the package.json, change the version for
1. angular-formio from ^4.8.0 to 4.9.3-rc.6
2. formiojs from ^4.10.0 to v4.11.1-rc.6
3. run npm install
4. In the renderer.component.ts declare a new object, say formToRender with the value 
```js
{
    "components": [
      {
          "label": "Text Field 1",
          "tableView": true,
          "customDefaultValue": "value=\"abc\"",
          "key": "textField",
          "type": "textfield",
          "input": true
      },
      {
          "label": "Text Field 2",
          "tableView": true,
          "calculateValue": "value=data.textField;",
          "allowCalculateOverride": true,
          "key": "textField1",
          "type": "textfield",
          "input": true
      },
      {
          "type": "button",
          "label": "Submit",
          "key": "submit",
          "disableOnInvalid": true,
          "input": true,
          "tableView": false
      }
  ]
}
```
5. Use this object to render the form in renderer.component.html as 
   <formio [form]="formToRender"></formio>

4. run npm start

## Expected behavior

The 'Text Field 2' field should have an initial value 'abc'

## Observed behavior

The value for 'Text Field 2' is empty.

## Note
1. The same JSON holds good when rendered using https://formio.github.io/formio.js/app/builder. 'Text Field 2' has the value 'abc' on rendering.

2. When I use formiojs as a script, refer https://jsfiddle.net/AmeeBhadania/y53fqdmu/ , things seem to work as expected. 'Text Field 2' has the value 'abc' on rendering.

**Comment by AmeeBhadania** [comment]
Any updates on this?

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
