### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by A-Pradeep** [formio/angular-demo#4]
I tried to install on Win10 but i'm getting the error 
```
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Angular Form.IO\angular-demo-master\node_modules\.staging\bootswatch-56c346ef\dist\cyborg\_bootswatch.scss'
.
.
.
npm WARN tar ENOENT: no such file or directory, open 'C:\Users\Angular Form.IO\angular-demo-master\node_modules\.staging\@angular\core-1332f2ff\src\render3\view_ref.d.ts'
npm WARN formio-angular-demo@1.3.0 No repository field.
npm WARN formio-angular-demo@1.3.0 No license field.

npm ERR! Maximum call stack size exceeded
```

Any ways to solve this issue.

**Comment by travist** [comment]
I am not sure what the ```.staging``` directory is here. I have not seen that before. This project just came from the Angular CLI, so are you able to run a blank project in Angular CLI.

**Comment by A-Pradeep** [comment]
It was the angular problem.
I was working on older version & that caused the issue.
Reinstall the angular & solved the problem.

Sorry for false issue 😅. You can close the issue
