### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Mkaith** [formio/angular-demo#46]
I have been trying to integrate form builder in my angular 12 application.

I did following things
import { FormioModule } from 'angular-formio'; -> added to app.module.ts

In my html
<form-builder [form]="form" (change)="onChange($event)"></form-builder>
<div class="well jsonviewer">
  <pre id="json"><code class="language-json" #json></code></pre>
</div>

And corresponding ts file is :-
import { Component, OnInit } from '@angular/core';
import { ElementRef, ViewChild } from '@angular/core';

@Component({
  selector: 'app-submission',
  templateUrl: './submission.component.html',
  styleUrls: ['./submission.component.scss']
})
export class SubmissionComponent implements OnInit {
  ngOnInit(): void {
    throw new Error('Method not implemented.');
  }

  @ViewChild('json') jsonElement?: ElementRef;
  public form: Object = {
    components: []
  };

  onChange(event:any) {
    console.log(event);
    //this.jsonElement.nativeElement.innerHTML = '';
    //this.jsonElement.nativeElement.appendChild(document.createTextNode(JSON.stringify(event.form, null, 4)));
  }
}

Error received:- 

Error: src/app/submission/submission.component.html:1:30 - error TS2532: Object is possibly 'undefined'.

1 <form-builder [form]="form" (change)="onChange($event)"></form-builder>
                                                  ~~~~~~

  src/app/submission/submission.component.ts:6:16
    6   templateUrl: './submission.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component SubmissionComponent.

observation:-
error in the change event.
Also after removing change it works fine but i need it. Pls reply if i am missing anything

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
