### ISSUE TITLE
problem with default value and multiple values option in data grid

### ISSUE THREAD

**Issue by hossein69** [formio/angular-demo#5]
bug appear after:
1-creating data grid with some component(example text field)
2-add option of multiple values in display panel.
3- going to data panel and add some rows.
4-save the data grid and enter some data or view form
5-try editing data grid become impossible.example trying to remove a column and bug appear.

**Comment by hossein69** [comment]
i create a sample in your demo project if you try to remove or edit a column the bug will happen.

**Comment by travist** [comment]
This sounds like a bug, so we will add this to our planning. Not sure if the priority would high, so if you need this soon, then you may need to dive into the code and debug it yourself. Here is the library that controls this behavior. https://github.com/formio/formio.js.

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
