### ISSUE TITLE
[info] 

### ISSUE THREAD

**Issue by siddharthaweb** [formio/angular-demo#53]
## Environment
Please provide as many details as you can:

- Hosting type
  - Local deployment
  - Version: 2.7.0
  - frontend Source: https://github.com/formio/angular-demo/tree/fix/angular-version-update

## Need information
after submitting a form, how to get the formID and submissionID.
our goal is to insert the formID and submissionID into another DB. 
also used form.io as admin panel: https://github.com/formio/formio

**Comment by jeriah-formio** [comment]
We're currently addressing a backlog of GitHub issues. Closing this thread as it is outdated. Please re-open if it is still relevant. Thank you for your contribution!
