### ISSUE TITLE
Registering custom component

### ISSUE THREAD

**Issue by adelaaji** [formio/angular-demo#6]
Hi all, 

I'm new to formio js, 

I'm trying to add custom component but it failed,
after that I download this demo and run it as is it,
![image](https://user-images.githubusercontent.com/5038461/54854675-bbf34100-4d04-11e9-9015-0db0da7f984b.png)

But custom component doesn't shown !!

??

**Comment by merobal** [comment]
See this as example: https://github.com/formio/angular-formio/wiki/Custom-Components-with-Angular-Elements#register-a-single-class-as-custom-component
