### ISSUE TITLE
Failed to compile with the Custom component CheckMatrix

### ISSUE THREAD

**Issue by senvaitis** [formio/angular-demo#8]
## Environment

- Hosting type: Local deployment

- npm: 6.9.0
- Global packages: 
   @angular/cli@8.3.5
- OS:
  Windows 10

## Steps to Reproduce
1. `git clone git@github.com:formio/angular-demo.git`
2. Uncomment `// import './components/CheckMatrix';` in `app.module.ts`
3. npm install
4. ng serve
 

## Expected behavior
Successful compilation

## Observed behavior
```
PS D:\work\sources\formio\angular-demo> ng serve
Your global Angular CLI version (8.3.5) is greater than your local
version (8.3.3). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
10% building 4/4 modules 0 activei ｢wds｣: Project is running at http://localhost:4200/webpack-dev-server/
i ｢wds｣: webpack output is served from /
i ｢wds｣: 404s will fallback to //index.html

chunk {auth-auth-module} auth-auth-module.js, auth-auth-module.js.map (auth-auth-module) 14.5 kB  [rendered]
chunk {event-event-module} event-event-module.js, event-event-module.js.map (event-event-module) 15.4 kB  [rendered]
chunk {form-form-module} form-form-module.js, form-form-module.js.map (form-form-module) 252 kB  [rendered]
chunk {forms-forms-module} forms-forms-module.js, forms-forms-module.js.map (forms-forms-module) 104 kB  [rendered]
chunk {main} main.js, main.js.map (main) 278 kB [initial] [rendered]
chunk {participant-participant-module} participant-participant-module.js, participant-participant-module.js.map (participant-participant-module) 3.7 kB  [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 287 kB [initial] [rendered]
chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 607 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 9.19 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 380 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 1.02 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 10.9 MB [initial] [rendered]
Date: 2019-09-23T11:01:52.021Z - Hash: bea2db4e6da4ec84ea6d - Time: 33202ms

ERROR in ./src/app/components/CheckMatrix.js 34:21
Module parse failed: Unexpected token (34:21)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   }
|
>   static builderInfo = {
|     title: 'Check Matrix',
|     group: 'basic',
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
i ｢wdm｣: Failed to compile.
```
## Additional details
Application runs fine when `import './components/CheckMatrix'; from app.module.ts` is commented.

**Comment by Indrajeetsing** [comment]
It still doesn't solve the problem. Getting same error. And when i replace static with following I don't get that error but still I don't see custom component is list.

`constructor(component, options, data) {
    super(component, options, data);
    this.builderInfo = {
      title: 'Check Matrix',
      group: 'basic',
      icon: 'fa fa-table',
      weight: 70,
      documentation: 'http://help.form.io/userguide/#table',
      schema: CheckMatrix.schema()
    };
    this.editForm = editForm;
 }`

**Comment by hadirsa** [comment]
I have the same issue:

```
ERROR in ./src/app/components/CheckMatrix.js 34:21
Module parse failed: Unexpected token (34:21)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|   }
| 
>   static builderInfo = {
|     title: 'Check Matrix',
|     group: 'basic',

```

**Comment by dcmadushani** [comment]
I am also facing the same issue with the uncommented custom component. Please help me to resolve this.

Error: ./src/app/components/CheckMatrix.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: C:\Projects\Infor\Formio\angular-demo-master\src\app\components\CheckMatrix.js: Support for the experimental syntax 'classProperties' isn't currently enabled (38:22):

  36 |   }
  37 | 
> 38 |   static builderInfo = {
     |                      ^
  39 |     title: 'Check Matrix',
  40 |     group: 'basic',
  41 |     icon: 'fa fa-table',
