### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by remouen** [formio/angular-demo#83]
## Environment
Please provide as many details as you can:

- Hosting type
  - [x] Form.io
  - [ ] Local deployment
    - Version: 
- Formio.js version:
- Frontend framework:
- Browser:
- Browser version:

## Steps to Reproduce
1. git clone the project
2. run npm install command line

## Expected behavior
instaling the node packages
## Observed behavior
Errors : 

> npm ERR! code ERESOLVE
> npm ERR! ERESOLVE could not resolve
> npm ERR! 
> npm ERR! While resolving: @angular-devkit/build-angular@13.3.9
> npm ERR! Found: karma@5.2.3
> npm ERR! node_modules/karma
> npm ERR!   dev karma@"^5.2.3" from the root project
> npm ERR!   peer karma@"*" from karma-jasmine@4.0.2
> npm ERR!   node_modules/karma-jasmine
> npm ERR!     dev karma-jasmine@"~4.0.0" from the root project
> npm ERR!     peer karma-jasmine@">=1.1" from karma-jasmine-html-reporter@1.7.0
> npm ERR!     node_modules/karma-jasmine-html-reporter
> npm ERR!       dev karma-jasmine-html-reporter@"^1.5.0" from the root project 
> npm ERR!   1 more (karma-jasmine-html-reporter)
> npm ERR! 
> npm ERR! Could not resolve dependency:
> npm ERR! peerOptional karma@"^6.3.0" from @angular-devkit/build-angular@13.3.9
> npm ERR! node_modules/@angular-devkit/build-angular
> npm ERR!   dev @angular-devkit/build-angular@"^13.3.6" from the root project  
> npm ERR! 
> npm ERR! Conflicting peer dependency: karma@6.4.1
> npm ERR! node_modules/karma
> npm ERR!   peerOptional karma@"^6.3.0" from @angular-devkit/build-angular@13.3.9
> npm ERR!   node_modules/@angular-devkit/build-angular
> npm ERR!     dev @angular-devkit/build-angular@"^13.3.6" from the root project
> npm ERR!
> npm ERR! Fix the upstream dependency conflict, or retry
> npm ERR! this command with --force or --legacy-peer-deps
> npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
> npm ERR!

## Example
If possible, please provide a screenshot, live example (via [JSFiddle](https://jsfiddle.net/) or similar), and/or example code to help demonstrate the issue.

For code or form JSON, please enclose in a code block:

```js
// your code here
```

**Comment by brendanbond** [comment]
If you're using npm, the error message tells you what to do here:

> npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

Run `npm i --legacy-peer-deps`
