### ISSUE TITLE
"static" in CheckMatrix

### ISSUE THREAD

**Issue by dmenne** [formio/angular-demo#9]
This could be a variant of #8. Since all links to custom component on Google link to this example, it would be important to get it to work.

I do not fully understand the rather [confusing state of "static" in Javascript ](https://github.com/tc39/proposal-static-class-features) and [Babel](https://babeljs.io/blog/2019/03/19/7.4.0), but all my compiler settings (including the original from github) give an error for 
`static builderInfo`. Putting it into the constructor works syntaxtically.

Nevertheless, `CheckMatrix`does not appear in the Builder.

```
 constructor(component, options, data) {
    super(component, options, data);
    this.builderInfo = {
      title: 'Check Matrix',
      group: 'basic',
      icon: 'fa fa-table',
      weight: 70,
      documentation: 'http://help.form.io/userguide/#table',
      schema: CheckMatrix.schema()
    };
  this.editForm = editForm;
  }

```

**Comment by dmenne** [comment]
Old style static works
```
// Use the table component edit form.
CheckMatrix.editForm = editForm;
CheckMatrix.builderInfo = {
  title: 'Check Matrix',
  group: 'basic',
  icon: 'fa fa-table',
  weight: 70,
  documentation: 'http://help.form.io/userguide/#table',
  schema: CheckMatrix.schema()
};

// Register the component to the Formio.Components registry.
Components.addComponent('checkmatrix', CheckMatrix);

```

**Comment by ashleyasli** [comment]
Hello,

I faced the same issue and your solution works for me. However, when I tried to implement "Checkmatrix" component into the form-builder, It doesn't appear in the form-builder.
I defined the form-builder like this: 
 
```
<form-builder [options]= '{
  "builder": {
    "basic": false,
    "advanced": false,
    "data": false,
    "layout": false,  
    "customBasic": {      
      "title": "Basic Components",
      "weight": 0,
      "default": false,      
      "components": {  
        "checkmatrix": true
      }
    }    
}}'
[form]="form" class="formio" (change)="onChange($event)"></form-builder>
```

and I got this error message. (Seen below)

![image](https://user-images.githubusercontent.com/43186823/66953433-1e56ba80-f024-11e9-8f2f-c977603c8fa4.png)

I am also attaching my link. If you want to look at what I changed on the "angular-demo" project to compile.

[https://github.com/ashleyasli/Formio-CustomComponent/commit/3d4fa03040d3c24c21b4e4ba07c55980f80be04d](url)

If you faced the same issue, could you please share your solution ? 

Thanks
